// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZOMzkQ_6vF_t78dueQ5MiFhg7z7C8zaI',
    appId: '1:599568182498:web:849ec800249899cb3242bb',
    messagingSenderId: '599568182498',
    projectId: 'minisfms',
    authDomain: 'minisfms.firebaseapp.com',
    storageBucket: 'minisfms.firebasestorage.app',
    measurementId: 'G-2Q7R51HR8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3OPQnY-rQLuBZLJ04Y0efqJgVy2zjsKw',
    appId: '1:599568182498:android:103f7dc4093d18373242bb',
    messagingSenderId: '599568182498',
    projectId: 'minisfms',
    storageBucket: 'minisfms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEBXdosx-dv5KVI2HgZWN60tFOBVAknKc',
    appId: '1:599568182498:ios:0bb72472967d491c3242bb',
    messagingSenderId: '599568182498',
    projectId: 'minisfms',
    storageBucket: 'minisfms.firebasestorage.app',
    iosBundleId: 'com.example.mpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEBXdosx-dv5KVI2HgZWN60tFOBVAknKc',
    appId: '1:599568182498:ios:0bb72472967d491c3242bb',
    messagingSenderId: '599568182498',
    projectId: 'minisfms',
    storageBucket: 'minisfms.firebasestorage.app',
    iosBundleId: 'com.example.mpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZOMzkQ_6vF_t78dueQ5MiFhg7z7C8zaI',
    appId: '1:599568182498:web:b1794783283ffc803242bb',
    messagingSenderId: '599568182498',
    projectId: 'minisfms',
    authDomain: 'minisfms.firebaseapp.com',
    storageBucket: 'minisfms.firebasestorage.app',
    measurementId: 'G-5Y6Z4GB1KV',
  );
}
